export default {
    todoForm: document.querySelector('#todo-form'),
    editForm: document.querySelector('#edit-form'),
    todoList: document.getElementById('todo-list'),
    archiveList: document.getElementById('archive-list'),
    item: document.querySelector('.todo-item'),
    summary: document.querySelector('.summary'),
    addTodoButton:document.querySelector('.add-todo-btn'),
    addTodoSubmitButton: document.getElementById('add-todo-submit'),
    archiveButton: document.getElementById('archive'),
    deleteAllButton: document.getElementById('delete-all'),
    saveChangesButton: document.querySelector('.save-changes-btn'),
    body: document.querySelector('body'),
    todoLightBox: document.querySelector('.todo-lightbox'),
    editLightBox:document.querySelector('.edit-lightbox'),
    archiveLightBox: document.querySelector('.archive-lightbox'),
};